name = "pjp-perfect-json-parser"
compatibility_date = "2024-01-20"

[env.production]
account_id = "your-account-id-here"
zone_id = "your-zone-id-here"

[[env.production.routes]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[pages]
build_output_dir = ".svelte-kit/cloudflare" 